name: Push docker image

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: true

      - name: Get deps for multi-arch build
        run: go mod vendor

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ inputs.service-name }}:latest
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.ref_name }}
