name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: true

      - name: Create assets
        run: |
          chmod +x ./scripts/release.sh
          ./scripts/release.sh

      - name: Prepare release draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: |
            ./release/*.zip
            ./release/*.tar.gz
